### ISSUE TITLE
KeyError and potential solution in sampling tutorial

### ISSUE THREAD

**Issue by adamkova** [EPFL-LCSB/pytfa#28]
Dear Pierre and colleagues,

First of all, thank you for the great tool, the neat support in the docs and the informative articles.

A minor issue/suggestion: 
In _tutorial_sampling.py_, using model _iJO1366.json_, I got a KeyError  on line 72, while applying flux directionality. Going into the code in _/analysis/manipulation.py_, I found that if I change the end of the code on line 70 from
`backward_use.variable.lb = round(solution.x_dict[backward_use.name])`
to
`backward_use.variable.lb = round(solution.x_dict[backward_use.id])`
and similarly for the other three lines as well, I can enforce the use of the raw id name, without the "BU_" and "FU_" prefixes. 

Not sure if it was a common issue, but in case anyone else would run into the same, this solved my problem.

Keep up the great work!

Best, Adam

**Comment by psalvy** [comment]
Good day Adam!

Thank you for the kind words :) We appreciate that people read our prose and use our tools !

Indeed, I forgot to adapt this part of the code to the new fields of the solution attribute. The problem of your solution is that `backward_use.id` will yield for example `PGI` instead of `BU_PGI`, and `PGI` is the variable name of the reaction PGI -- which might create some issues since that would mean bounding an integer with continuous values ;) (This also explains why you do not get a key error)

However, i replaced `solution.x_dict` by  `solution.raw`, which yields the raw Series of variable values at solution - this should work. Try pulling from dev (commit  b9f14d27b5a2f616ba0917ae69b2f6d88f1abc11) - and tell me if that solves your problem :)

Cheers,
Pierre

**Comment by adamkova** [comment]
Hi Pierre,

Appreciate the quick response and the update! You are right, I was binding the integers inappropriately... After pulling the update, it works like a charm, thanks. 

Subsequently, I found `x_dict`s to be replaced in `/analysis/variability.py` as well. Would the below changes make sense (as per your previous update)? 
77: `profiles[iter_count] = solution.x_dict` &rarr; `profiles[iter_count] = solution.raw`
207: `fluxes = solution.x_dict[reaction_id]` &rarr; `fluxes = solution.raw[reaction_id]`
210: `deltag = pd.Series({x.id:solution.x_dict[x.name]` &rarr; `deltag = pd.Series({x.id:solution.raw[x.name]`

In the case of line 207, I am a bit confused about the deprecated `x_dict`s from `cobrapy` (which were suggested to be changed to `fluxes`) and these `x_dict`s that should be changed to `raw`. Can you maybe suggest an intuitive way to differentiate them? This `pytfa - cobrapy` integration and tracking the attributes/variables gets a bit tricky for me at certain points... :)

Thanks ahead!
Adam

**Comment by psalvy** [comment]
Good day Adam,

Thank you for pointing these out!
Yes, I kinda coded this in a hurry without proper documentation ... Here was my reasoning:

* `solution.fluxes` in `cobrapy` is a transformed version of the solver output, as it actually calculates the _net_ flux of each reaction by substracting the reverse variable value to the forward variable value. This should be used anytime one needs the actual flux value

* `solution.raw` is an attribute I added to get a clear copy of the solver output. From there one can access the value at solution for all the variables of the problem. However, looking for a reaction ID in there will only give the _forward_ flux. This should be used for any other variable than fluxes.

I did not want to remove fluxes from `solution.raw` because then, well, it would not be raw anymore ...
However if you have suggestions with respect to this I would gladly take them !
I should have corrected the last remnants of `x_dict` in the latest push (dev, commit a985ce897b3787f53e358cf73c314531b820454c)

Let me know if that solved your plroblem, and I'll close the issue :)

Cheers,
Pierre

**Comment by adamkova** [comment]
Good day to you too, Pierre,

Thank you for the new update and the detailed explanation. The pace at which you addressed these issues is impressive :+1:. 

This thumb rule about the use cases of `fluxes` and `raw` makes good sense to me now. I also agree that for completeness, `solution.raw` should contain everything.

The changes seem to have done the trick, the code regained its flow.

Regarding suggestions, I would not make any now. It is a big project, and I could see that it takes quite some time to get a good enough overview of what is happening under the hood. Momentarily, it seems more feasible to assume that you made all the right choices during coding. :)

With that, please feel free to close this issue.

Keep it up,
Adam
