### ISSUE TITLE
tutorial_basic.py ERROR - Relaxation could not complete (no DeltaG relaxation found)

### ISSUE THREAD

**Issue by Dahlai** [EPFL-LCSB/pytfa#40]
Dear pyTFA team,
I tried running the tutorial_basics.py script (after you helped me understand the warnings) which gave me a result for the regular thermodynamics FBA. However, when trying to run the second part of the script where a relaxed model is generated the script throws the following error:

> thermomodel_new - ERROR - Relaxation could not complete (no DeltaG relaxation found)

According to the annotation in the source code this either means the model is infeasible or something else went wrong. Could you hint at what I'm doing wrong here?

Thanks a lot.

Cheers,
Michael

**Comment by psalvy** [comment]
Good day Michael,

Thank you for using pyTFA!
Could you please tell me what solver you are using ? And check the solver status `model.solver.status`, as well as the time limit of the solver `model.solver.configuration.timeout` ?
Cheers,
Pierre

**Comment by Dahlai** [comment]
Hi Pierre, 
thanks for getting back to me.

I tried GLPK and Gurobi and in both cases I get the error.

The attributes have the same value for both GLPK and Gurobi:
`mytfa.solver.status = 'optimal'`
`mytfa.solver.configuration.timeout = None`

Cheers,
Michael

**Comment by psalvy** [comment]
Good day Michael,

I apologize, my previous answer was not very clear. Could you give me the status of the solver after the error occurs?
Also, can you tell  me if you are running the master or the dev or a Pypi version of pyTFA?

Cheers,
Pierre

**Comment by Dahlai** [comment]
Hi Pierre,
I installed pyTFA from PyPI (version 0.9.1).

The errors are posted after the error occurs, see below:

`if True:   # substituted the if condition to always end up in the relaxation mode
    from pytfa.optim.relaxation import relax_dgo

    mytfa.reactions.get_by_id(biomass_rxn).lower_bound = 0.5*fba_value
    relaxed_model, slack_model, relax_table = relax_dgo(mytfa)

    original_model, mytfa = mytfa, relaxed_model

    print('Relaxation: ')
    print(relax_table)
    
    tfa_solution = mytfa.optimize()
    tfa_value = tfa_solution.objective_value

print(mytfa.solver.status)
print(mytfa.solver.configuration.timeout)`

Cheers,
Michael

**Comment by psalvy** [comment]
Good day Michael, 

I see you replaced the `if` condition, with a `True` statement -- I assume you are doing this to "force" a relaxation ?

I just downloaded the same version of pyTFA as you, and ran the tutorial file without an issue. 

So I think the problem is that you are asking for a relaxation of the model, while it is already feasible. In that case, the relaxation is null, as no slack has to be given to allow the model to be feasible, and you get an error from [L. 240 of `relax_dgo`](https://github.com/EPFL-LCSB/pytfa/blob/58a0b86a49f2b111815f43aaa1538523c6c76336/pytfa/optim/relaxation.py#L241). 

If you want to experiment with relaxation, you can set a lower bound to the biomass reaction that is higher than the currently achievable specific growth rate (although the scientific meaning of this is limited ;) ). We usually use relaxation for cases where, upon integrating experimental data, the model becomes infeasible.

Hope that helps!

Cheers,
Pierre

**Comment by Dahlai** [comment]
Hi Pierre,
I understand now. I figured it would still just loosen the thermodynamic constraints and then rerun the model thus just giving the same result. 

Thank you for clarifying this.

Cheers,
Michael

**Comment by psalvy** [comment]
Yes you are right, maybe the documentation needs to be clearer about that :)
Happy to help !
Cheers,
Pierre
